"""osvScanNode (백로그 34 DEV-2 2차, ADR-0034) — lockfile 파서·OSV 조회 계약 테스트.

  1. **일곱 형식을 내용으로 알아본다.** 파일 이름이 없다 — 앞 노드 출력으로 들어온다.
  2. **querybatch 계약대로 부른다.** 1,000개씩 나눠 보내고, 결과 순서를 패키지에 맞춘다. 상세는 취약점마다 한 번, 50개 상한.
  3. **취약점은 결과다.** 있어도 예외가 아니고, failOnVulnerable 을 켠 그래프에서만 OSV_VULNERABLE.
"""

from __future__ import annotations

import json

import pytest

import mock_service
import node_definition
from connectors import mock as mock_fixtures
from connectors.errors import ConnectorError
from connectors.services import osv
from connectors.session import ConnectorSession, Response
from text_tools import ToolError

DEFINITION = node_definition.get_definition("osvScanNode")

PACKAGE_LOCK_V3 = json.dumps({"name": "app", "lockfileVersion": 3, "packages": {
    "": {"name": "app", "version": "1.0.0"},
    "node_modules/lodash": {"version": "4.17.20"},
    "node_modules/a/node_modules/lodash": {"version": "4.17.19"},
    "node_modules/@scope/pkg": {"version": "2.0.0"},
    "node_modules/linked": {"link": True, "version": "0.0.1"},
}})
PACKAGE_LOCK_V1 = json.dumps({"name": "app", "lockfileVersion": 1, "dependencies": {
    "lodash": {"version": "4.17.20", "dependencies": {"nested": {"version": "1.0.0"}}}}})
YARN = '''# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@scope/pkg@^2.0.0":
  version "2.0.1"
  resolved "https://registry.yarnpkg.com/@scope/pkg/-/pkg-2.0.1.tgz"

lodash@^4.17.0, lodash@~4.17.19:
  version "4.17.21"
'''
REQUIREMENTS = "# deps\nDjango==4.2.1\nrequests[security]==2.31.0 \\\n  --hash=sha256:abc\n-r other.txt\nflask>=2.0\nPyYAML == 6.0.1  # yaml\n"
PIPFILE_LOCK = json.dumps({"_meta": {"hash": {}}, "default": {"django": {"version": "==4.2.1"}}, "develop": {"pytest": {"version": "==8.0.0"}}})
POETRY = '[[package]]\nname = "Django"\nversion = "4.2.1"\n\n[[package]]\nname = "requests"\nversion = "2.31.0"\n\n[metadata]\nlock-version = "2.0"\ncontent-hash = "x"\n'
GO_SUM = "github.com/gin-gonic/gin v1.9.1 h1:abc=\ngithub.com/gin-gonic/gin v1.9.1/go.mod h1:def=\ngolang.org/x/text v0.14.0 h1:ghi=\n"
CARGO = '# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = "serde"\nversion = "1.0.190"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\n'


# ── 1. 파서 ───────────────────────────────────────────────────────────────

@pytest.mark.parametrize("text, fmt, expected", [
    (PACKAGE_LOCK_V3, "package-lock", {("lodash", "4.17.20", "npm"), ("lodash", "4.17.19", "npm"), ("@scope/pkg", "2.0.0", "npm")}),
    (PACKAGE_LOCK_V1, "package-lock", {("lodash", "4.17.20", "npm"), ("nested", "1.0.0", "npm")}),
    (YARN, "yarn", {("@scope/pkg", "2.0.1", "npm"), ("lodash", "4.17.21", "npm")}),
    (REQUIREMENTS, "requirements", {("django", "4.2.1", "PyPI"), ("requests", "2.31.0", "PyPI"), ("pyyaml", "6.0.1", "PyPI")}),
    (PIPFILE_LOCK, "pipfile-lock", {("django", "4.2.1", "PyPI"), ("pytest", "8.0.0", "PyPI")}),
    (POETRY, "poetry-lock", {("django", "4.2.1", "PyPI"), ("requests", "2.31.0", "PyPI")}),
    (GO_SUM, "go-sum", {("github.com/gin-gonic/gin", "1.9.1", "Go"), ("golang.org/x/text", "0.14.0", "Go")}),
    (CARGO, "cargo-lock", {("serde", "1.0.190", "crates.io")}),
])
def test_일곱_형식을_내용으로_알아보고_패키지를_뽑는다(text, fmt, expected):
    detected, packages = osv.parse_lockfile(text)
    assert detected == fmt
    assert {(p["name"], p["version"], p["ecosystem"]) for p in packages} == expected


def test_형식을_지정하면_감지를_건너뛴다():
    detected, packages = osv.parse_lockfile(REQUIREMENTS, "requirements")
    assert detected == "requirements" and len(packages) == 3


@pytest.mark.parametrize("text, detail", [("", "empty"), ("그냥 문장입니다", "undetected"), ("{bad json", "undetected"), ('{"a": 1}', "undetected"),
                                          ("flask>=2.0\n", "undetected")])
def test_읽지_못하면_OSV_LOCKFILE_UNRECOGNIZED(text, detail):
    with pytest.raises(ToolError) as exc:
        osv.parse_lockfile(text)
    assert exc.value.reason == "OSV_LOCKFILE_UNRECOGNIZED" and exc.value.safe_details["detail"] == detail


def test_지정한_형식으로_읽다_실패해도_같은_코드():
    with pytest.raises(ToolError) as exc:
        osv.parse_lockfile("not json", "package-lock")
    assert exc.value.reason == "OSV_LOCKFILE_UNRECOGNIZED" and exc.value.safe_details["detail"] == "package-lock"
    with pytest.raises(ToolError):
        osv.parse_lockfile(REQUIREMENTS, "zip")


# ── 2. 조회 ───────────────────────────────────────────────────────────────

class _OsvTransport:
    def __init__(self, vulns_by_index=None, details=None, fail_status=None):
        self.calls = []
        self.vulns_by_index = vulns_by_index or {}
        self.details = details or {}
        self.fail_status = fail_status

    def __call__(self, method, url, **kwargs):
        self.calls.append({"method": method, "url": url, **kwargs})
        if self.fail_status:
            return Response(status=self.fail_status, headers={}, body={"message": "boom"})
        if url.endswith("/v1/querybatch"):
            queries = kwargs["json"]["queries"]
            offset = sum(len(c["json"]["queries"]) for c in self.calls[:-1] if c["url"].endswith("/v1/querybatch"))
            results = [{"vulns": self.vulns_by_index.get(offset + i, [])} if self.vulns_by_index.get(offset + i) else {} for i in range(len(queries))]
            return Response(status=200, headers={}, body={"results": results})
        vuln_id = url.rsplit("/", 1)[-1]
        return Response(status=200, headers={}, body=self.details.get(vuln_id, {"id": vuln_id}))


def _session(transport):
    return ConnectorSession("OSV", transport=transport, sleep=lambda _s: None)


DETAIL = {
    "GHSA-1": {"id": "GHSA-1", "summary": "Prototype pollution", "aliases": ["CVE-2020-8203"], "database_specific": {"severity": "HIGH"},
               "affected": [{"package": {"ecosystem": "npm", "name": "lodash"}, "ranges": [{"type": "SEMVER", "events": [{"introduced": "0"}, {"fixed": "4.17.21"}]}]}]},
    "GHSA-2": {"id": "GHSA-2", "summary": "ReDoS", "aliases": [], "database_specific": {"severity": "MODERATE"},
               "affected": [{"package": {"ecosystem": "npm", "name": "lodash"}, "ranges": [{"type": "SEMVER", "events": [{"introduced": "0"}, {"fixed": "4.17.20"}]}]}]},
    "GHSA-3": {"id": "GHSA-3", "summary": "unknown sev", "affected": []},
}


def test_querybatch_계약과_상세_조회_그리고_정렬():
    t = _OsvTransport(vulns_by_index={0: [{"id": "GHSA-1", "modified": "m"}, {"id": "GHSA-2"}], 2: [{"id": "GHSA-3"}]}, details=DETAIL)
    result = osv.scan(DEFINITION, PACKAGE_LOCK_V3, session=_session(t))
    batch = t.calls[0]
    assert batch["method"] == "POST" and batch["url"] == "https://api.osv.dev/v1/querybatch"
    assert batch["json"]["queries"][0] == {"package": {"name": "lodash", "ecosystem": "npm"}, "version": "4.17.20"}
    assert [c["url"].rsplit("/", 1)[-1] for c in t.calls[1:]] == ["GHSA-1", "GHSA-2", "GHSA-3"], "상세는 취약점마다 한 번"
    assert result["packages"] == 3 and result["queried"] == 3 and result["vulnerable"] == 2 and result["alertCount"] == 3
    assert [a["id"] for a in result["alerts"]] == ["GHSA-1", "GHSA-2", "GHSA-3"], "심각도 높은 것부터"
    top = result["alerts"][0]
    assert top["severity"] == "HIGH" and top["fixedVersion"] == "4.17.21" and top["aliases"] == ["CVE-2020-8203"]
    assert top["url"] == "https://osv.dev/vulnerability/GHSA-1" and top["package"] == "lodash" and top["version"] == "4.17.20"
    assert result["bySeverity"] == {"LOW": 0, "MODERATE": 1, "HIGH": 1, "CRITICAL": 0, "UNKNOWN": 1}
    assert result["format"] == "package-lock" and result["ecosystem"] == "npm" and result["truncated"] is False


def test_최소_심각도_필터는_미상을_제외하고_수를_남긴다():
    t = _OsvTransport(vulns_by_index={0: [{"id": "GHSA-1"}, {"id": "GHSA-2"}], 2: [{"id": "GHSA-3"}]}, details=DETAIL)
    result = osv.scan(DEFINITION, PACKAGE_LOCK_V3, min_severity="HIGH", session=_session(t))
    assert [a["id"] for a in result["alerts"]] == ["GHSA-1"] and result["vulnerable"] == 1 and result["unknownSeveritySkipped"] == 1
    with pytest.raises(ConnectorError):
        osv.scan(DEFINITION, PACKAGE_LOCK_V3, min_severity="SEVERE", session=_session(_OsvTransport()))


def test_1000개씩_나눠_보내고_maxPackages_로_자른다():
    lines = "\n".join(f"pkg{i}==1.0.{i}" for i in range(1500))
    t = _OsvTransport()
    result = osv.scan(DEFINITION, lines, include_details=False, max_packages=1200, session=_session(t))
    batches = [len(c["json"]["queries"]) for c in t.calls]
    assert batches == [1000, 200] and result["queried"] == 1200 and result["packages"] == 1500 and result["truncated"] is True


def test_상세_없이도_id_와_링크는_남는다():
    t = _OsvTransport(vulns_by_index={0: [{"id": "GHSA-1", "modified": "2024-01-01T00:00:00Z"}]})
    result = osv.scan(DEFINITION, PACKAGE_LOCK_V3, include_details=False, session=_session(t))
    assert len(t.calls) == 1 and result["alerts"][0]["severity"] == "UNKNOWN" and result["alerts"][0]["url"].endswith("GHSA-1")
    assert result["alerts"][0]["modified"] == "2024-01-01T00:00:00Z"


def test_OSV_서버_오류는_커넥터_오류다():
    with pytest.raises(ConnectorError) as exc:
        osv.scan(DEFINITION, REQUIREMENTS, session=_session(_OsvTransport(fail_status=503)))
    assert exc.value.code == "server_error"


def test_severity_는_database_specific_를_우선하고_없으면_UNKNOWN():
    assert osv.severity_of({"database_specific": {"severity": "critical"}}) == "CRITICAL"
    assert osv.severity_of({"affected": [{"ecosystem_specific": {"severity": "LOW"}}]}) == "LOW"
    assert osv.severity_of({"severity": [{"type": "CVSS_V3", "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"}]}) == "UNKNOWN"


# ── 3. 정의·mock·그래프 ──────────────────────────────────────────────────────

def test_정의는_자격증명_없는_읽기_전용_커넥터다():
    assert DEFINITION.connector.required_providers() == [] and DEFINITION.connector.writes_externally("scan") is False
    assert not mock_fixtures.validate_mock(DEFINITION.mock, DEFINITION.connector, label="osvScanNode")
    assert DEFINITION.connector.baseUrl == osv.BASE_URL


def _graph(data, payload, scenario="success"):
    graph = {"nodes": [{"id": "w1", "type": "webhookNode", "data": {}}, {"id": "s1", "type": "osvScanNode", "data": data},
                       {"id": "o1", "type": "outputNode", "data": {}}],
             "edges": [{"id": "e1", "source": "w1", "target": "s1"}, {"id": "e2", "source": "s1", "target": "o1"}]}
    result = mock_service.run(graph, db=None, project_id=1, entry_node_id="w1", payload=payload, scenario=scenario)
    return result, next(s for s in result["logs"] if s.get("node_id") == "s1")


def test_목업_그래프에서_직전_출력의_lockfile_을_읽고_취약점을_결과로_준다():
    result, step = _graph({}, PACKAGE_LOCK_V3)
    assert result["success"] is True, result["result"]
    out = json.loads(step["result_data"])
    assert out["format"] == "package-lock" and out["alertCount"] >= 1 and out["alerts"][0]["package"] == "lodash"
    assert out["alerts"][0]["severity"] == "HIGH" and out["alerts"][0]["fixedVersion"] == "4.17.21" and step.get("error") is None
    assert [q["method"] for q in result["requests"]][:1] == ["POST"]


def test_failOnVulnerable_이면_OSV_VULNERABLE_로_error_갈래():
    _, step = _graph({"failOnVulnerable": True}, PACKAGE_LOCK_V3)
    assert (step.get("error") or {}).get("code") == "OSV_VULNERABLE"
    _, unrecognized = _graph({}, "그냥 텍스트")
    assert (unrecognized.get("error") or {}).get("code") == "OSV_LOCKFILE_UNRECOGNIZED"
    _, down = _graph({}, PACKAGE_LOCK_V3, scenario="server_error")
    assert (down.get("error") or {}).get("code") not in (None, "OSV_VULNERABLE"), "서버 오류는 커넥터 오류로 남는다"
