import datetime
from node_registry import node_registry

@node_registry.register('templateAnalyzerNode')
def generate_template_analyzer_node(node_id, node, indent, active_llm_id, prev_res_var, visited, node_dict, forward_edges, incoming_edges, lines, generate_block_fn):
    lines.append(f"{indent}# --- Template Analyzer Node ({node_id}) ---")
    lines.append(f"{indent}_start_{node_id} = datetime.datetime.utcnow().isoformat()")
    template_file = node.get('data', {}).get('template_path', '').replace('"', '\\"').replace('\n', '\\n').replace('\\', '/')
    lines.append(f"{indent}try:")
    lines.append(f"{indent}    import re")
    lines.append(f"{indent}    import json")
    lines.append(f"{indent}    import os")
    lines.append(f"{indent}    template_ext = \"{template_file}\".lower()")
    lines.append(f"{indent}    extracted_keys = set()")
    lines.append(f"{indent}    full_text = ''")
    lines.append(f"{indent}    if template_ext.endswith('.hwp') or template_ext.endswith('.hwpx'):")
    lines.append(f"{indent}        import pythoncom")
    lines.append(f"{indent}        pythoncom.CoInitialize()")
    lines.append(f"{indent}        from pyhwpx import Hwp")
    lines.append(f"{indent}        hwp = Hwp(visible=False)")
    lines.append(f"{indent}        try:")
    lines.append(f"{indent}            hwp.open(os.path.abspath(\"{template_file}\"))")
    lines.append(f"{indent}            hwp.InitScan()")
    lines.append(f"{indent}            while True:")
    lines.append(f"{indent}                status, text = hwp.GetText()")
    lines.append(f"{indent}                if status in [0, 1]: break")
    lines.append(f"{indent}                full_text += text")
    lines.append(f"{indent}            hwp.ReleaseScan()")
    lines.append(f"{indent}            field_str = hwp.get_field_list(1, 0)")
    lines.append(f"{indent}            if field_str:")
    lines.append(f"{indent}                for field in field_str.split('\\x02'):")
    lines.append(f"{indent}                    if field.strip(): extracted_keys.add(field.strip())")
    lines.append(f"{indent}        finally:")
    lines.append(f"{indent}            hwp.quit()")
    lines.append(f"{indent}    elif template_ext.endswith('.xlsx') or template_ext.endswith('.xls'):")
    lines.append(f"{indent}        import openpyxl")
    lines.append(f"{indent}        wb = openpyxl.load_workbook(\"{template_file}\")")
    lines.append(f"{indent}        for sheet in wb.worksheets:")
    lines.append(f"{indent}            for row in sheet.iter_rows():")
    lines.append(f"{indent}                for cell in row:")
    lines.append(f"{indent}                    if cell.value and isinstance(cell.value, str):")
    lines.append(f"{indent}                        full_text += cell.value + ' '")
    lines.append(f"{indent}    elif template_ext.endswith('.pptx') or template_ext.endswith('.ppt'):")
    lines.append(f"{indent}        from pptx import Presentation")
    lines.append(f"{indent}        prs = Presentation(\"{template_file}\")")
    lines.append(f"{indent}        for slide in prs.slides:")
    lines.append(f"{indent}            for shape in slide.shapes:")
    lines.append(f"{indent}                if shape.has_text_frame:")
    lines.append(f"{indent}                    for p in shape.text_frame.paragraphs:")
    lines.append(f"{indent}                        for run in p.runs:")
    lines.append(f"{indent}                            if run.text:")
    lines.append(f"{indent}                                full_text += run.text + ' '")
    lines.append(f"{indent}    else:")
    lines.append(f"{indent}        with open(\"{template_file}\", \"r\", encoding=\"utf-8\", errors='ignore') as f:")
    lines.append(f"{indent}            full_text = f.read()")
    lines.append(f"{indent}    ")
    lines.append(indent + "    found_keys = re.findall(r'\\{\\{([^}]+)\\}\\}', full_text)")
    lines.append(f"{indent}    for k in found_keys:")
    lines.append(f"{indent}        extracted_keys.add(k.strip())")
    lines.append(f"{indent}    ")
    lines.append(f"{indent}    schema_dict = {{k: '' for k in extracted_keys}}")
    lines.append(f"{indent}    res_val_{node_id} = json.dumps(schema_dict, ensure_ascii=False, indent=2)")
    lines.append(f"{indent}except Exception as e:")
    lines.append(f"{indent}    res_val_{node_id} = f'Error analyzing template: {{str(e)}}'")
    lines.append(f"{indent}last_result = res_val_{node_id}")
    
    lines.append(f"{indent}log_step('{node_id}', '{node['type']}', _start_{node_id}, result=last_result)")
    next_edges = forward_edges.get(node_id, [])
    for target_id, handle in next_edges:
        generate_block_fn(target_id, indent, active_llm_id=active_llm_id, prev_res_var=f"res_val_{node_id}", visited=visited)


@node_registry.register('fileModifierNode')
def generate_file_modifier_node(node_id, node, indent, active_llm_id, prev_res_var, visited, node_dict, forward_edges, incoming_edges, lines, generate_block_fn):
    lines.append(f"{indent}# --- Auto Fill Node ({node_id}) ---")
    lines.append(f"{indent}_start_{node_id} = datetime.datetime.utcnow().isoformat()")
    template_file = node.get('data', {}).get('template_path', '').replace('"', '\\"').replace('\n', '\\n').replace('\\', '/')
                    
    output_file = node.get('data', {}).get('output_path', '').replace('"', '\\"').replace('\n', '\\n')
    if not output_file:
        if template_file:
            ext = template_file.split('.')[-1]
            output_file = f"output.{ext}"
        else:
            output_file = "output.txt"
    
    if not output_file.startswith('uploads/') and not output_file.startswith('uploads\\\\'):
        import os as _os
        output_file = 'uploads/' + _os.path.basename(output_file)
    lines.append(f"{indent}try:")
    lines.append(f"{indent}    import json")
    lines.append(f"{indent}    import os")
    lines.append(f"{indent}    data_in = {prev_res_var if prev_res_var else 'last_result'}")
    lines.append(f"{indent}    if isinstance(data_in, str):")
    lines.append(f"{indent}        try:")
    lines.append(f"{indent}            data_dict = json.loads(data_in)")
    lines.append(f"{indent}        except: data_dict = {{}}")
    lines.append(f"{indent}    elif isinstance(data_in, dict):")
    lines.append(f"{indent}        data_dict = data_in")
    lines.append(f"{indent}    else:")
    lines.append(f"{indent}        data_dict = {{}}")
    lines.append(f"{indent}    ")
    lines.append(f"{indent}    template_ext = \"{template_file}\".lower()")
    lines.append(f"{indent}    if template_ext.endswith('.hwp') or template_ext.endswith('.hwpx'):")
    lines.append(f"{indent}        import pythoncom")
    lines.append(f"{indent}        pythoncom.CoInitialize()")
    lines.append(f"{indent}        from pyhwpx import Hwp")
    lines.append(f"{indent}        hwp = Hwp(visible=False)")
    lines.append(f"{indent}        try:")
    lines.append(f"{indent}            hwp.open(os.path.abspath(\"{template_file}\"))")
    lines.append(f"{indent}            for k, v in data_dict.items():")
    lines.append(f"{indent}                hwp.put_field_text(str(k), str(v))")
    lines.append(f"{indent}                hwp.find_replace_all('{{{{' + str(k) + '}}}}', str(v))")
    lines.append(f"{indent}            hwp.save_as(os.path.abspath(\"{output_file}\"))")
    lines.append(f"{indent}        finally:")
    lines.append(f"{indent}            hwp.quit()")
    lines.append(f"{indent}    elif template_ext.endswith('.xlsx') or template_ext.endswith('.xls'):")
    lines.append(f"{indent}        import openpyxl")
    lines.append(f"{indent}        wb = openpyxl.load_workbook(\"{template_file}\")")
    lines.append(f"{indent}        for sheet in wb.worksheets:")
    lines.append(f"{indent}            for row in sheet.iter_rows():")
    lines.append(f"{indent}                for cell in row:")
    lines.append(f"{indent}                    if cell.value and isinstance(cell.value, str):")
    lines.append(f"{indent}                        for k, v in data_dict.items():")
    lines.append(f"{indent}                            if '{{{{' + str(k) + '}}}}' in cell.value:")
    lines.append(f"{indent}                                cell.value = cell.value.replace('{{{{' + str(k) + '}}}}', str(v))")
    lines.append(f"{indent}        wb.save(\"{output_file}\")")
    lines.append(f"{indent}    elif template_ext.endswith('.pptx') or template_ext.endswith('.ppt'):")
    lines.append(f"{indent}        from pptx import Presentation")
    lines.append(f"{indent}        prs = Presentation(\"{template_file}\")")
    lines.append(f"{indent}        for slide in prs.slides:")
    lines.append(f"{indent}            for shape in slide.shapes:")
    lines.append(f"{indent}                if shape.has_text_frame:")
    lines.append(f"{indent}                    for p in shape.text_frame.paragraphs:")
    lines.append(f"{indent}                        for run in p.runs:")
    lines.append(f"{indent}                            if run.text:")
    lines.append(f"{indent}                                for k, v in data_dict.items():")
    lines.append(f"{indent}                                    if '{{{{' + str(k) + '}}}}' in run.text:")
    lines.append(f"{indent}                                        run.text = run.text.replace('{{{{' + str(k) + '}}}}', str(v))")
    lines.append(f"{indent}        prs.save(\"{output_file}\")")
    lines.append(f"{indent}    else:")
    lines.append(f"{indent}        with open(\"{output_file}\", \"w\", encoding=\"utf-8\") as _f:")
    lines.append(f"{indent}            _f.write(str({prev_res_var if prev_res_var else 'last_result'}))")
    lines.append(f"{indent}    ")
    lines.append(f"{indent}    res_text_{node_id} = \"{output_file}\"")
    lines.append(f"{indent}except Exception as e:")
    lines.append(f"{indent}    res_text_{node_id} = f\"Error formatting file: {{str(e)}}\"")
    lines.append(f"{indent}last_result = res_text_{node_id}")
    
    lines.append(f"{indent}log_step('{node_id}', '{node['type']}', _start_{node_id}, result=last_result)")
    next_edges = forward_edges.get(node_id, [])
    for target_id, handle in next_edges:
        generate_block_fn(target_id, indent, active_llm_id=active_llm_id, prev_res_var=f"res_text_{node_id}", visited=visited)


@node_registry.register('tokenizerNode')
def generate_tokenizer_node(node_id, node, indent, active_llm_id, prev_res_var, visited, node_dict, forward_edges, incoming_edges, lines, generate_block_fn):
    method = node.get('data', {}).get('method', 'extract_text')
    lines.append(f"{indent}# --- Tokenizer Node ({node_id}) ---")
    lines.append(f"{indent}_start_{node_id} = datetime.datetime.utcnow().isoformat()")
    lines.append(f"{indent}file_path_raw = {prev_res_var if prev_res_var else 'last_result'}")
    lines.append(f"{indent}import re")
    lines.append(f"{indent}match_{node_id} = re.search(r'\\[Attached File: (.*?)\\]', str(file_path_raw))")
    lines.append(f"{indent}if match_{node_id}:")
    lines.append(f"{indent}    file_path = match_{node_id}.group(1)")
    lines.append(f"{indent}else:")
    lines.append(f"{indent}    file_path = str(file_path_raw)")
    lines.append(f"{indent}res_text_{node_id} = []")
    
    lines.append(f"{indent}if str(file_path).lower().endswith('.pdf'):")
    lines.append(f"{indent}    import PyPDF2")
    lines.append(f"{indent}    with open(file_path, 'rb') as f:")
    lines.append(f"{indent}        reader = PyPDF2.PdfReader(f)")
    if method == 'chunk_pages':
        lines.append(f"{indent}        res_text_{node_id} = [page.extract_text() for page in reader.pages]")
    else:
        lines.append(f"{indent}        res_text_{node_id} = ['\\n'.join([page.extract_text() for page in reader.pages])]")
        
    lines.append(f"{indent}elif str(file_path).lower().endswith('.xlsx') or str(file_path).lower().endswith('.xls'):")
    lines.append(f"{indent}    import pandas as pd")
    if method == 'chunk_pages':
        lines.append(f"{indent}    df = pd.read_excel(file_path, sheet_name=None)")
        lines.append(f"{indent}    res_text_{node_id} = [f'Sheet: {{sheet}}\\n{{df[sheet].to_string()}}' for sheet in df.keys()]")
    else:
        lines.append(f"{indent}    df = pd.read_excel(file_path)")
        lines.append(f"{indent}    res_text_{node_id} = [df.to_string()]")
        
    lines.append(f"{indent}elif str(file_path).lower().endswith('.pptx'):")
    lines.append(f"{indent}    from pptx import Presentation")
    lines.append(f"{indent}    prs = Presentation(file_path)")
    if method == 'chunk_pages':
        lines.append(f"{indent}    for slide in prs.slides:")
        lines.append(f"{indent}        slide_text = []")
        lines.append(f"{indent}        for shape in slide.shapes:")
        lines.append(f"{indent}            if hasattr(shape, 'text'): slide_text.append(shape.text)")
        lines.append(f"{indent}        res_text_{node_id}.append('\\n'.join(slide_text))")
    else:
        lines.append(f"{indent}    full_text = []")
        lines.append(f"{indent}    for slide in prs.slides:")
        lines.append(f"{indent}        for shape in slide.shapes:")
        lines.append(f"{indent}            if hasattr(shape, 'text'): full_text.append(shape.text)")
        lines.append(f"{indent}    res_text_{node_id} = ['\\n'.join(full_text)]")

    lines.append(f"{indent}elif str(file_path).lower().endswith('.hwp'):")
    lines.append(f"{indent}    try:")
    lines.append(f"{indent}        import olefile")
    lines.append(f"{indent}        import zlib")
    lines.append(f"{indent}        import struct")
    lines.append(f"{indent}        f = olefile.OleFileIO(file_path)")
    lines.append(f"{indent}        dirs = f.listdir()")
    lines.append(f"{indent}        if ['PrvText'] in dirs:")
    lines.append(f"{indent}            text = f.openstream('PrvText').read().decode('utf-16le')")
    lines.append(f"{indent}            res_text_{node_id} = [text]")
    lines.append(f"{indent}        else:")
    lines.append(f"{indent}            body_dirs = [d for d in dirs if d[0] == 'BodyText']")
    lines.append(f"{indent}            text = ''")
    lines.append(f"{indent}            for d in body_dirs:")
    lines.append(f"{indent}                unpacked_data = zlib.decompress(f.openstream(d).read(), -15)")
    lines.append(f"{indent}                i = 0")
    lines.append(f"{indent}                while i < len(unpacked_data):")
    lines.append(f"{indent}                    header = struct.unpack_from('<I', unpacked_data, i)[0]")
    lines.append(f"{indent}                    tag_id = header & 0x3FF")
    lines.append(f"{indent}                    size = (header >> 20) & 0xFFF")
    lines.append(f"{indent}                    if size == 0xFFF:")
    lines.append(f"{indent}                        size = struct.unpack_from('<I', unpacked_data, i + 4)[0]")
    lines.append(f"{indent}                        i += 8")
    lines.append(f"{indent}                    else:")
    lines.append(f"{indent}                        i += 4")
    lines.append(f"{indent}                    if tag_id == 67:")
    lines.append(f"{indent}                        try:")
    lines.append(f"{indent}                            decoded = unpacked_data[i:i+size].decode('utf-16le')")
    lines.append(f"{indent}                            text += ''.join(c for c in decoded if ord(c) >= 32 or c in '\\n\\r\\t') + '\\n'")
    lines.append(f"{indent}                        except: pass")
    lines.append(f"{indent}                    i += size")
    lines.append(f"{indent}            if text.strip():")
    lines.append(f"{indent}                res_text_{node_id} = [text]")
    lines.append(f"{indent}            else:")
    lines.append(f"{indent}                import subprocess")
    lines.append(f"{indent}                res = subprocess.run(['hwp5txt', file_path], capture_output=True, text=True, encoding='utf-8')")
    lines.append(f"{indent}                res_text_{node_id} = [res.stdout] if res.stdout else ['[Error or empty: hwp5txt]']")
    lines.append(f"{indent}    except Exception as e:")
    lines.append(f"{indent}        res_text_{node_id} = [str(e)]")

    lines.append(f"{indent}elif str(file_path).lower().endswith('.hwpx'):")
    lines.append(f"{indent}    import zipfile")
    lines.append(f"{indent}    import xml.etree.ElementTree as ET")
    lines.append(f"{indent}    try:")
    lines.append(f"{indent}        with zipfile.ZipFile(file_path, 'r') as zf:")
    lines.append(f"{indent}            sec_files = [f for f in zf.namelist() if f.startswith('Contents/section') and f.endswith('.xml')]")
    lines.append(f"{indent}            hwpx_text = []")
    lines.append(f"{indent}            for sec in sorted(sec_files):")
    lines.append(f"{indent}                root = ET.fromstring(zf.read(sec))")
    lines.append(f"{indent}                for elem in root.iter():")
    lines.append(f"{indent}                    if elem.tag.endswith('}}t') or elem.tag.endswith(':t'):")
    lines.append(f"{indent}                        if elem.text: hwpx_text.append(elem.text)")
    lines.append(f"{indent}                hwpx_text.append('\\n')")
    lines.append(f"{indent}            res_text_{node_id} = [''.join(hwpx_text)]")
    lines.append(f"{indent}    except Exception as e:")
    lines.append(f"{indent}        res_text_{node_id} = [str(e)]")
    
    lines.append(f"{indent}elif str(file_path).lower().endswith(('.txt', '.csv', '.md', '.json', '.html')):")
    lines.append(f"{indent}    try:")
    lines.append(f"{indent}        with open(file_path, 'r', encoding='utf-8') as f:")
    lines.append(f"{indent}            res_text_{node_id} = [f.read()]")
    lines.append(f"{indent}    except Exception as e:")
    lines.append(f"{indent}        res_text_{node_id} = [f'Text Read Error: {{str(e)}}']")

    lines.append(f"{indent}if res_text_{node_id}:")
    lines.append(f"{indent}    parsed_str_{node_id} = '\\n'.join(res_text_{node_id})")
    lines.append(f"{indent}    if match_{node_id}:")
    lines.append(f"{indent}        last_result = str(file_path_raw).replace(match_{node_id}.group(0), f'[Parsed Content:]\\n{{parsed_str_{node_id}}}\\n')")
    lines.append(f"{indent}    else:")
    lines.append(f"{indent}        last_result = parsed_str_{node_id}")
    lines.append(f"{indent}else:")
    lines.append(f"{indent}    last_result = str(file_path_raw)")
    
    lines.append(f"{indent}log_step('{node_id}', '{node['type']}', _start_{node_id}, result=last_result)")
    next_edges = forward_edges.get(node_id, [])
    for target_id, handle in next_edges:
        generate_block_fn(target_id, indent, active_llm_id=active_llm_id, prev_res_var=f"res_text_{node_id}", visited=visited)
