import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import { useAuth } from '../AuthContext';
import { formatDate, timeAgo } from '../timeFormat';
import { customConfirm } from '../CustomConfirm';
import { Eye, EyeOff, PencilLine, Play, Plus, Trash2, Workflow } from 'lucide-react';
import MainSidebar from '../MainSidebar';
import './MainPage.css';
import './ManagementPage.css';

function WorkflowsPage() {
  const navigate = useNavigate();
  const { user, token } = useAuth();
  const [myProjects, setMyProjects] = useState([]);
  const [myLoading, setMyLoading] = useState(true);
  const [showHidden, setShowHidden] = useState(false);

  const isAutoGenerated = (desc) => desc && desc.startsWith("Auto-generated backend workflow");
  const filteredProjects = myProjects.filter(p => showHidden || !isAutoGenerated(p.description));
  const hiddenProjectCount = myProjects.filter(p => isAutoGenerated(p.description)).length;

  const fetchMyProjects = async () => {
    if (!token) { setMyLoading(false); return; }
    setMyLoading(true);
    try {
      const res = await axios.get('/api/projects/my', { headers: { Authorization: `Bearer ${token}` } });
      setMyProjects(res.data);
    } catch (error) {
      console.error('Error fetching my projects:', error);
    } finally {
      setMyLoading(false);
    }
  };

  useEffect(() => { fetchMyProjects(); }, [user, token]);

  const handleDelete = async (projectId) => {
    if (!(await customConfirm("정말로 이 워크플로우를 삭제하시겠습니까?"))) return;
    try {
      await axios.delete(`/api/projects/${projectId}`, { headers: { Authorization: `Bearer ${token}` } });
      setMyProjects(prev => prev.filter(p => p.id !== projectId));
    } catch (error) {
      console.error("Failed to delete project", error);
      alert("프로젝트 삭제에 실패했습니다.");
    }
  };

  const handleAppRun = async (project) => {
    let sToken = project.share_token;
    if (!sToken) {
      try {
        const res = await axios.post(`/api/projects/${project.id}/deploy`, {}, { headers: { Authorization: `Bearer ${token}` } });
        sToken = res.data.share_token;
      } catch (error) {
        console.error("Failed to prepare app run", error);
        alert("앱 실행 준비에 실패했습니다.");
        return;
      }
    }
    navigate(`/app/${sToken}`);
  };

  return (
    <div className="main-page-layout">
      <MainSidebar />
      <main className="main-page-content management-page">
        <div className="management-content">
          <header className="management-header">
            <div className="management-heading">
              <span className="management-kicker">WORKFLOWS</span>
              <h1>내 워크플로우</h1>
              <p>만든 자동화를 한곳에서 확인하고 편집하거나, 실행 가능한 앱으로 바로 열어보세요.</p>
            </div>
            <div className="management-header-side" aria-label="워크플로우 요약">
              <div className="management-stat"><span>전체</span><strong>{myProjects.length}</strong></div>
              <div className="management-stat"><span>표시 중</span><strong>{filteredProjects.length}</strong></div>
              <button className="management-button primary" onClick={() => navigate('/editor')}>
                <Plus size={15} /> 새 워크플로우
              </button>
            </div>
          </header>

          <div className="management-toolbar">
            <span className="management-toolbar-label">최근 수정된 순서로 작업물을 표시합니다.</span>
            <div className="management-toolbar-actions">
              {hiddenProjectCount > 0 && (
                <label className="management-toggle">
                  <input type="checkbox" checked={showHidden} onChange={(e) => setShowHidden(e.target.checked)} />
                  {showHidden ? <Eye size={13} /> : <EyeOff size={13} />}
                  앱 백엔드 {hiddenProjectCount}개
                </label>
              )}
            </div>
          </div>

          {!user ? (
            <div className="management-empty"><h2>로그인이 필요합니다</h2><p>로그인 후 내 워크플로우를 확인할 수 있습니다.</p></div>
          ) : myLoading ? (
            <div className="management-loading" aria-label="워크플로우를 불러오는 중">{[0, 1, 2, 3].map(item => <span key={item} />)}</div>
          ) : filteredProjects.length === 0 ? (
            <div className="management-empty">
              <span className="management-empty-icon"><Workflow size={20} /></span>
              <h2>{hiddenProjectCount > 0 ? '표시할 워크플로우가 없습니다' : '아직 저장된 워크플로우가 없습니다'}</h2>
              <p>{hiddenProjectCount > 0 ? '앱 백엔드 표시 옵션을 켜거나 새 워크플로우를 만들어보세요.' : '빈 캔버스에 노드를 놓고 연결하면 첫 자동화가 만들어집니다.'}</p>
              <button className="management-button primary" onClick={() => navigate('/editor')}><Plus size={14} /> 첫 워크플로우 만들기</button>
            </div>
          ) : (
            <div className="management-grid">
              {filteredProjects.map(project => {
                const visibilityLabel = project.visibility === 'public' ? '공개' : project.visibility === 'friends' ? '친구 공개' : '비공개';
                return (
                  <article key={project.id} className="management-card">
                    <div className="management-card-body">
                      <div className="management-card-top">
                        <span className="management-resource"><span className="management-resource-icon"><Workflow size={14} /></span> WORKFLOW</span>
                        <div className="management-card-tools">
                          <span className={`management-status ${project.is_live ? 'active' : 'stopped'}`}><span className="management-status-dot" />{project.is_live ? '실행 중' : '중지'}</span>
                          <span className={`management-status visibility-${project.visibility || 'private'}`}><span className="management-status-dot" />{visibilityLabel}</span>
                          <button
                            type="button"
                            className="management-icon-button danger"
                            onClick={() => handleDelete(project.id)}
                            title="워크플로우 삭제"
                            aria-label={`${project.title} 삭제`}
                          >
                            <Trash2 size={14} />
                          </button>
                        </div>
                      </div>
                      <h2 title={project.title}>{project.title || '제목 없는 워크플로우'}</h2>
                      <p className="management-card-description">{project.description || '설명이 아직 추가되지 않았습니다.'}</p>
                      <div className="management-meta-grid">
                        <span className="management-meta-item"><span>구성</span><strong>{project.node_count ?? 0}개 노드 · {project.edge_count ?? 0}개 연결</strong></span>
                        <span className="management-meta-item"><span>리비전</span><strong>v{project.current_revision ?? 0}</strong></span>
                        <span className="management-meta-item"><span>최근 수정</span><strong>{timeAgo(project.updated_at)}</strong></span>
                        <span className="management-meta-item"><span>생성일</span><strong>{formatDate(project.created_at)}</strong></span>
                        <span className="management-meta-item"><span>배포</span><strong>{project.share_token ? '앱 링크 생성됨' : '미배포'}</strong></span>
                        <span className="management-meta-item"><span>프로젝트 ID</span><code>#{project.id}</code></span>
                        {isAutoGenerated(project.description) && <span className="management-meta-item"><span>용도</span><strong>앱 빌더 백엔드</strong></span>}
                      </div>
                    </div>
                    <footer className="management-card-actions">
                      <button className="management-button primary" onClick={() => navigate(`/editor/${project.id}`)}>
                        <PencilLine size={14} /> 편집하기
                      </button>
                      <button className="management-button" onClick={() => handleAppRun(project)}>
                        <Play size={14} /> 앱 실행
                      </button>
                    </footer>
                  </article>
                );
              })}
            </div>
          )}
        </div>
      </main>
    </div>
  );
}

export default WorkflowsPage;
