// 실제로 생성·검수된 공식 템플릿 자산만 노출한다. 아직 제작하지 않은 공식 템플릿은
// 존재하지 않는 URL을 요청하지 않고 목록의 기본 빈 썸네일을 그대로 사용한다.
const GENERATED_OFFICIAL_TEMPLATE_SLUGS = new Set([
  'wf-ai',
  'wf-wf-2',
  'wf-ai-2',
  'wf-wf-3',
  'q-a',
  'wf-wf-4',
  'wf-wf-8',
  'wf-wf-9',
  'seo',
  'gmail',
  'slack',
  'sql',
  'wf-wf-18',
  'csv',
  'wf-wf-21',
  'wf-wf-22',
  'api-q-a',
  'wf-wf-25',
  'wf-wf-27',
  'wf-wf-28',
  'wf-wf-33',
  'wf-wf-35',
  'wf-wf-36',
  'wf-it',
  'q-a-2',
  'wf-wf-40',
  'wf-wf-41',
  'q-a-3',
  'wf-wf-42',
  'wf-wf-43',
  'wf-wf-44',
  'wf-wf-45',
  'faq',
  'sns',
  'wf-wf-46',
  'pdf-2',
  'pdf-3',
  'wf-wf-47',
  'wf-wf-50',
  'wf-wf-52',
  'wf-wf-54',
  'wf-wf-55',
  'q-a-4',
  'wf-wf-56',
  'wf-wf-57',
  'api-3',
  'wf-wf-59',
  'wf-wf-60',
  'wf-wf-61',
  'wf-wf-62',
  'wf-wf-63',
  'wf-wf-64',
  'wf-wf-65',
  'wf-wf-67',
  'wf-wf-68',
  'wf-wf-69',
  'wf-wf-74',
  'wf-wf-78',
  'wf-wf-79',
  'wf-wf-80',
  'wf-wf-81',
  'wf-wf-82',
  'wf-wf-83',
  'wf-wf-84',
  'wf-wf-85',
  'wf-wf-86',
  'wf-wf-87',
  'wf-wf-88',
  'wf-wf-89',
  'wf-wf-90',
  'nda',
  'wf-wf-95',
  'wf-wf-96',
  'wf-wf-100',
  'wf-wf-101',
  'wf-wf-102',
  'wf-wf-103',
  'wf-wf-104',
  'url',
  'wf-wf-106',
  'wf-wf-105',
  'wf-wf-108',
  'wf-wf-107',
  'wf-wf-109',
  'wf-wf-113',
  'wf-wf-111',
  'wf-wf-187',
  'wf-wf-189',
  'wf-wf-190',
]);

export function getTemplateThumbnail(template) {
  if (template?.thumbnailUrl) return template.thumbnailUrl;
  if (!template?.isCurated || !GENERATED_OFFICIAL_TEMPLATE_SLUGS.has(template.slug)) {
    return null;
  }

  const baseUrl = import.meta.env.BASE_URL || '/';
  return `${baseUrl}official-template-thumbnails/${encodeURIComponent(template.slug)}.webp`;
}
