"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-08-28 00:36:04.104291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('billable_user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('execution_time', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('token_usage_details', sa.JSON(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flow_execution_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_execution_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_execution_logs_billable_user_id'), ['billable_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_execution_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_execution_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_execution_logs_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_execution_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_execution_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_execution_logs_trigger_type'), ['trigger_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_execution_logs_user_id'), ['user_id'], unique=False)

    op.create_table('node_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('history', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_memory_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_memory_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_memory_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_memory_session_id'), ['session_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('token_balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('custom_apps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('ui_graph_data', sa.JSON(), nullable=True),
    sa.Column('workflow_mappings', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_apps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_apps_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_apps_owner_id'), ['owner_id'], unique=False)

    op.create_table('evaluation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('test_case_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_logs_user_id'), ['user_id'], unique=False)

    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friend_requests_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friend_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friend_requests_to_user_id'), ['to_user_id'], unique=False)

    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_friend_id'), ['friend_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_user_id'), ['user_id'], unique=False)

    op.create_table('generation_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('request_kind', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model_profile', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('task_spec_prompt_version', sa.String(), nullable=True),
    sa.Column('repair_prompt_version', sa.String(), nullable=True),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('request_length', sa.Integer(), nullable=True),
    sa.Column('request_preview', sa.String(), nullable=True),
    sa.Column('task_spec', sa.JSON(), nullable=True),
    sa.Column('graph_summary', sa.JSON(), nullable=True),
    sa.Column('validation_issues', sa.JSON(), nullable=True),
    sa.Column('repair_notes', sa.JSON(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('langfuse_trace_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_traces_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_traces_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_traces_langfuse_trace_id'), ['langfuse_trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_traces_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_traces_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_traces_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_traces_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_traces_trace_id'), ['trace_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_generation_traces_user_id'), ['user_id'], unique=False)

    op.create_table('node_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_execution_id', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('node_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result_data', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['flow_execution_id'], ['flow_execution_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_execution_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_execution_logs_flow_execution_id'), ['flow_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_execution_logs_id'), ['id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('graph_data', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('share_token', sa.String(), nullable=True),
    sa.Column('deploy_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_share_token'), ['share_token'], unique=True)

    op.create_table('site_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_feedback_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('training_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('request_text', sa.String(), nullable=False),
    sa.Column('task_spec', sa.JSON(), nullable=True),
    sa.Column('generated_graph', sa.JSON(), nullable=False),
    sa.Column('final_graph', sa.JSON(), nullable=True),
    sa.Column('validation_issues', sa.JSON(), nullable=True),
    sa.Column('acceptance_status', sa.String(), nullable=True),
    sa.Column('edit_metrics', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('prompt_versions', sa.JSON(), nullable=True),
    sa.Column('consent_policy_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_examples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_examples_acceptance_status'), ['acceptance_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_examples_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_examples_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_examples_request_hash'), ['request_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_examples_trace_id'), ['trace_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_training_examples_user_id'), ['user_id'], unique=False)

    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_api_keys_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('bot_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_logs_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_bot_logs_id'))

    op.drop_table('bot_logs')
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_api_keys_provider'))
        batch_op.drop_index(batch_op.f('ix_user_api_keys_id'))

    op.drop_table('user_api_keys')
    with op.batch_alter_table('training_examples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_examples_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_examples_trace_id'))
        batch_op.drop_index(batch_op.f('ix_training_examples_request_hash'))
        batch_op.drop_index(batch_op.f('ix_training_examples_project_id'))
        batch_op.drop_index(batch_op.f('ix_training_examples_id'))
        batch_op.drop_index(batch_op.f('ix_training_examples_acceptance_status'))

    op.drop_table('training_examples')
    with op.batch_alter_table('site_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_site_feedback_id'))

    op.drop_table('site_feedback')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_share_token'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    with op.batch_alter_table('node_execution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_execution_logs_id'))
        batch_op.drop_index(batch_op.f('ix_node_execution_logs_flow_execution_id'))

    op.drop_table('node_execution_logs')
    with op.batch_alter_table('generation_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_traces_user_id'))
        batch_op.drop_index(batch_op.f('ix_generation_traces_trace_id'))
        batch_op.drop_index(batch_op.f('ix_generation_traces_thread_id'))
        batch_op.drop_index(batch_op.f('ix_generation_traces_status'))
        batch_op.drop_index(batch_op.f('ix_generation_traces_project_id'))
        batch_op.drop_index(batch_op.f('ix_generation_traces_outcome'))
        batch_op.drop_index(batch_op.f('ix_generation_traces_langfuse_trace_id'))
        batch_op.drop_index(batch_op.f('ix_generation_traces_id'))
        batch_op.drop_index(batch_op.f('ix_generation_traces_created_at'))

    op.drop_table('generation_traces')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_user_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_friend_id'))

    op.drop_table('friendships')
    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friend_requests_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_friend_requests_id'))
        batch_op.drop_index(batch_op.f('ix_friend_requests_from_user_id'))

    op.drop_table('friend_requests')
    with op.batch_alter_table('evaluation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_logs_id'))

    op.drop_table('evaluation_logs')
    with op.batch_alter_table('custom_apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_apps_owner_id'))
        batch_op.drop_index(batch_op.f('ix_custom_apps_id'))

    op.drop_table('custom_apps')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_project_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('node_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_memory_session_id'))
        batch_op.drop_index(batch_op.f('ix_node_memory_project_id'))
        batch_op.drop_index(batch_op.f('ix_node_memory_node_id'))
        batch_op.drop_index(batch_op.f('ix_node_memory_id'))

    op.drop_table('node_memory')
    with op.batch_alter_table('flow_execution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_execution_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_flow_execution_logs_trigger_type'))
        batch_op.drop_index(batch_op.f('ix_flow_execution_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_flow_execution_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_flow_execution_logs_outcome'))
        batch_op.drop_index(batch_op.f('ix_flow_execution_logs_id'))
        batch_op.drop_index(batch_op.f('ix_flow_execution_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_flow_execution_logs_billable_user_id'))
        batch_op.drop_index(batch_op.f('ix_flow_execution_logs_actor_user_id'))

    op.drop_table('flow_execution_logs')
    # ### end Alembic commands ###
