"""project revisions and optimistic concurrency

ADR-0006. project_revisions 테이블과 projects.current_revision 을 추가하고, 이미 있는
프로젝트에는 현재 graph_data 를 revision 1 로 백필한다 — 이 마이그레이션 직후부터 모든
프로젝트가 되돌릴 수 있는 지점을 하나씩 갖게 하려는 것이다(백필이 없으면 다음 저장까지
비교 대상이 없어서 첫 충돌에서 diff 를 못 보여준다).

Revision ID: 0002_project_revisions
Revises: 0001_baseline
Create Date: 2026-08-28 00:36:38.758749

"""
from typing import Sequence, Union

import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_project_revisions'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('graph_data', sa.JSON(), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'revision', name='uq_project_revision')
    )
    with op.batch_alter_table('project_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_revisions_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_revisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_revisions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_revisions_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_revision', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###

    _backfill_initial_revisions()


def _backfill_initial_revisions() -> None:
    """이미 있는 프로젝트의 현재 그래프를 revision 1 로 남긴다.

    이 제품은 사용자당 수동 워크플로우가 5개로 제한되어 있어 대상 행이 적다. 규모가 커지면
    배치로 나눠야 한다.
    """
    projects = sa.table(
        "projects",
        sa.column("id", sa.Integer),
        sa.column("user_id", sa.Integer),
        sa.column("title", sa.String),
        sa.column("description", sa.String),
        sa.column("graph_data", sa.JSON),
        sa.column("current_revision", sa.Integer),
    )
    revisions = sa.table(
        "project_revisions",
        sa.column("project_id", sa.Integer),
        sa.column("revision", sa.Integer),
        sa.column("title", sa.String),
        sa.column("description", sa.String),
        sa.column("graph_data", sa.JSON),
        sa.column("author_user_id", sa.Integer),
        sa.column("source", sa.String),
        sa.column("created_at", sa.DateTime),
    )

    connection = op.get_bind()
    rows = connection.execute(
        sa.select(
            projects.c.id, projects.c.user_id, projects.c.title,
            projects.c.description, projects.c.graph_data,
        )
    ).fetchall()
    if not rows:
        return

    now = datetime.datetime.utcnow()
    connection.execute(
        revisions.insert(),
        [
            {
                "project_id": row.id,
                "revision": 1,
                "title": row.title,
                "description": row.description,
                "graph_data": row.graph_data or {"nodes": [], "edges": []},
                "author_user_id": row.user_id,
                # 사용자가 그때 누른 저장이 아니라 마이그레이션이 떠온 스냅샷이라는 뜻.
                "source": "import",
                "created_at": now,
            }
            for row in rows
        ],
    )
    connection.execute(projects.update().values(current_revision=1))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('current_revision')

    with op.batch_alter_table('project_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_revisions_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_revisions_id'))
        batch_op.drop_index(batch_op.f('ix_project_revisions_created_at'))
        batch_op.drop_index(batch_op.f('ix_project_revisions_author_user_id'))

    op.drop_table('project_revisions')
    # ### end Alembic commands ###
