"""uploaded file ownership and retention

ADR-0010. 이미 디스크에 있는 파일들은 소유자를 알 수 없으므로 백필하지 않는다 — 지어낸
소유자를 붙이면 남의 용량으로 계산되거나 엉뚱한 파일이 정리 대상이 된다. 기록이 없는 기존
파일은 정리 작업이 건드리지 않고 그대로 둔다(코드에서 명시적으로 그렇게 처리한다).

Revision ID: 0003_uploaded_files
Revises: 0002_project_revisions
Create Date: 2026-08-28 03:41:46.211480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_uploaded_files'
down_revision: Union[str, Sequence[str], None] = '0002_project_revisions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stored_name', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_files_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_stored_name'), ['stored_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_uploaded_files_uploaded_by_user_id'), ['uploaded_by_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_uploaded_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_stored_name'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_project_id'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_id'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_expires_at'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_created_at'))

    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
